\documentclass[article,nojss]{jss}


<<package,include=FALSE,echo=FALSE>>=
options(keep.source = TRUE, width = 60)
packageInfo <- packageDescription("violinpoint")
library(violinpoint)
packageKeywords<-"visualization, display, one dimensional, grouped, groups, violin, scatter, points, quasirandom, beeswarm, van der Corput"
@
%\VignetteIndexEntry{\Sexpr{packageInfo$Package} method comparisons}
%\VignetteDepends{beeswarm}
%\VignetteKeywords{\Sexpr{packageKeywords}}
%\VignettePackage{\Sexpr{packageInfo$Package}}

\title{\pkg{\Sexpr{packageInfo$Package}} package example (version \Sexpr{packageInfo$Version})}
\author{\Sexpr{packageInfo$Author}}
\Plainauthor{\Sexpr{packageInfo$Author}}

\Address{
  Github: \url{http://github.com/sherrillmix/violinpoint}
}

\Keywords{\Sexpr{packageKeywords}}

\Abstract{
  This is a collection of examples of usage for the \pkg{\Sexpr{packageInfo$Package}} package.
}

\begin{document}
\SweaveOpts{engine=R,eps=FALSE}

\section{General description}

This is an example of using the \pkg{\Sexpr{packageInfo$Package}} package in R.
<<vpPlot, echo=FALSE, eval=FALSE>>=
  set.seed(1234)
  dat<-rnorm(100)
  vpPlot(rep(c('a','b'),50),dat)
@

\begin{figure}[htbp]
\begin{center}
<<showVpPlot, fig=TRUE, height=4.5, width=8, echo=FALSE>>=
<<vpPlot>>
@
\label{figVpPlot}
\caption{An example of a simple violin point call}
\end{center}
\end{figure}


\end{document}
